# Generated by Django 4.2.6 on 2023-10-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(null=True, verbose_name='Время выхода'),
        ),
    ]
