# Generated by Django 4.2.6 on 2023-10-13 16:57

import users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_alter_user_options_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=users.models.Role.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
    ]
