# Generated by Django 4.2.6 on 2023-10-15 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 10, 41, 56, 163874, tzinfo=datetime.timezone.utc), verbose_name='Время выхода'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=users.models.Role.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Роль'),
        ),
    ]
