# Generated by Django 4.2.6 on 2023-11-19 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_visit_login_time_alter_visit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='login_time',
            field=models.DateTimeField(default=datetime.now(), verbose_name='Время входа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
