# Generated by Django 4.2.6 on 2023-11-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_visit_login_time_alter_visit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Роль'),
        ),
    ]
