# Generated by Django 4.2.6 on 2023-10-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_office_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('make_model', models.CharField(max_length=255, verbose_name='Марка')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Количество сидений')),
                ('economy_seats', models.PositiveIntegerField(verbose_name='Мест в экономе')),
                ('business_seats', models.PositiveIntegerField(verbose_name='Мест в бизнес-классе')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, verbose_name='Код аэропорта')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Amentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
            },
        ),
        migrations.CreateModel(
            name='CabinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип кабины',
                'verbose_name_plural': 'Типы кабин',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='Дистанция полета')),
                ('flight_time', models.PositiveIntegerField(verbose_name='Время полета')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_airport', to='airports.airport', verbose_name='Аэропорт прибытия')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_airport', to='airports.airport', verbose_name='Аэропорт отправления')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('flight_number', models.CharField(max_length=255, verbose_name='Номер рейса')),
                ('economy_price', models.PositiveIntegerField(verbose_name='Стоимость эконома')),
                ('confirmed', models.BooleanField(verbose_name='Наличие подтверждения')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.aircraft', verbose_name='Самолет')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.route', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('passport_number', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('booking_reference', models.CharField(max_length=255, verbose_name='Номер брони')),
                ('confirmed', models.BooleanField(verbose_name='Наличие подтверждения')),
                ('cabin_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.cabintype', verbose_name='Тип кабины')),
                ('passport_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.country', verbose_name='Гражданство')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.schedule', verbose_name='Рейс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, default='NS', max_length=2, null=True, verbose_name='Пол')),
                ('q1', models.IntegerField(default=0, null=True, verbose_name='Оценка самолета')),
                ('q2', models.IntegerField(default=0, null=True, verbose_name='Оценка проводников')),
                ('q3', models.IntegerField(default=0, null=True, verbose_name='Оценка развлечений')),
                ('q4', models.IntegerField(default=0, null=True, verbose_name='Оценка стоимости')),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival', to='airports.airport', verbose_name='Куда')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departure', to='airports.airport', verbose_name='Откуда')),
                ('travel_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='airports.cabintype', verbose_name='Класс билета')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='AmentityTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('amentity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.amentity', verbose_name='Доп. услуга')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Билет с услугой',
                'verbose_name_plural': 'Билеты с услугами',
            },
        ),
    ]
