# Generated by Django 4.2.6 on 2023-10-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('make_model', models.CharField(max_length=255, verbose_name='Марка')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Количество сидений')),
                ('economy_seats', models.PositiveIntegerField(verbose_name='Мест в экономе')),
                ('business_seats', models.PositiveIntegerField(verbose_name='Мест в бизнес-классе')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, verbose_name='Код аэропорта')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.country')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='Дистанция полета')),
                ('flight_time', models.PositiveIntegerField(verbose_name='Время полета')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_airport', to='airports.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_airport', to='airports.airport')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.RenameField(
            model_name='office',
            old_name='country_id',
            new_name='country',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('flight_number', models.CharField(max_length=255, verbose_name='Номер рейса')),
                ('economy_price', models.PositiveIntegerField(verbose_name='Стоимость эконома')),
                ('confirmed', models.BooleanField(verbose_name='Наличие подтверждения')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.aircraft')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.route')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
