# Generated by Django 4.2.6 on 2023-10-27 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airports', '0002_aircraft_airport_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип кабины',
                'verbose_name_plural': 'Типы кабин',
            },
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='office',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_airport', to='airports.airport', verbose_name='Аэропорт прибытия'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_airport', to='airports.airport', verbose_name='Аэропорт отправления'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('passport_number', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('booking_reference', models.CharField(max_length=255, verbose_name='Номер брони')),
                ('confirmed', models.BooleanField(verbose_name='Наличие подтверждения')),
                ('cabin_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.cabintype', verbose_name='Тип кабины')),
                ('passport_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.country', verbose_name='Гражданство')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.schedule', verbose_name='Рейс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
