# Generated by Django 4.2.6 on 2023-10-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_alter_schedule_aircraft_alter_schedule_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, default='NS', max_length=2, null=True, verbose_name='Пол')),
                ('q1', models.IntegerField(default=0, null=True, verbose_name='Оценка самолета')),
                ('q2', models.IntegerField(default=0, null=True, verbose_name='Оценка проводников')),
                ('q3', models.IntegerField(default=0, null=True, verbose_name='Оценка развлечений')),
                ('q4', models.IntegerField(default=0, null=True, verbose_name='Оценка стоимости')),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival', to='airports.airport', verbose_name='Куда')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departure', to='airports.airport', verbose_name='Откуда')),
                ('travel_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='airports.cabintype', verbose_name='Класс билета')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
