# Generated by Django 4.2.6 on 2023-11-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_alter_aircraft_business_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Наличие подтверждения'),
        ),
    ]
