# Generated by Django 4.2.6 on 2023-10-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0005_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
            },
        ),
        migrations.CreateModel(
            name='AmentityTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('amentity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airports.amentity', verbose_name='Доп. услуга')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Билет с услугой',
                'verbose_name_plural': 'Билеты с услугами',
            },
        ),
    ]
